import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientSideMotion from "./components/ClientSideMotion";
import MenuBubbles from "./components/MenuBubbles";
import posts from "./data/posts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page-layout">
          {/* Corners */}
          <div className="border-container top-left-corner">
            {/* Top Left Corner Content */}
          </div>
          <div className="border-container top-right-corner">
            {/* Top Right Corner Content */}
          </div>
          <div className="border-container bottom-left-corner">
            {/* Bottom Left Corner Content */}
          </div>
          <div className="border-container bottom-right-corner">
            {/* Bottom Right Corner Content */}
          </div>

          {/* Borders */}
          <div className="border-container top-border">
            {/* Top Border Content */}
          </div>
          <div className="border-container bottom-border">
            {/* Bottom Border Content */}
          </div>
          <div className="border-container left-border">
            {/* Left Border Content */}
          </div>
          <div className="border-container right-border">
            {/* Right Border Content */}
          </div>

          {/* Main Content */}
          <div className="main-section">
            <div className="container">
              {/* Left Column - Menu Bubbles */}
              <div className="leftColumn">
                <MenuBubbles posts={posts} />
              </div>

              {/* Right Column - Content Area */}
              <div className="rightColumn">
                <ClientSideMotion>{children}</ClientSideMotion>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
